### ISSUE TITLE
ValueError:continuous format is not supported

### ISSUE THREAD

**Issue by renqiqi** [byungjae89/SPADE-pytorch#5]
Hi,
    When I trained the model on my own dataset, there is a problem: ValueError: continuous format is not supported.
    I have processed my dataset into the same form as MVtec. What is the reason?

**Comment by AlgirdasKartavicius** [comment]
Did you solve your problem?

**Comment by renqiqi** [comment]
> Did you solve your problem?

modify the code src/main.py:line 155

flatten_gt_mask_list = np.concatenate(gt_mask_list).ravel() 
flatten_gt_mask_list = flatten_gt_mask_list.astype('uint8')       
flatten_score_map_list = np.concatenate(score_map_list).ravel()

**Comment by AlgirdasKartavicius** [comment]
Thank you.
